name: zotero-rag-assistant
services:
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - core
      - webdav
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - UPSTREAM_HOST=api
      - UPSTREAM_PORT=8000

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    restart: unless-stopped
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma:/chroma/chroma

  core:
    build:
      context: ../
      dockerfile: ./infrastructure/core/Dockerfile
    container_name: core
    depends_on:
      - chroma
    environment:
      - OLLAMA_HOST=not-set
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - PROMPTS_DIR=/prompts
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - documents:/data
      - prompts:/prompts

  webdav:
    build: webdav/
    container_name: webdav
    depends_on:
      - core
    environment:
      - PORT=8000
      - ROOT_DIR=/var/lib/webdav/data
      - CORE_API_URL=http://core:8000/internal/file-changed
    volumes:
      - documents:/var/lib/webdav/data

volumes:
  documents:
  chroma:
  prompts:
