name: zotero-rag-assistant
services:
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - core
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - UPSTREAM_HOST=api
      - UPSTREAM_PORT=8000
  core:
    build:
      context: ../
      dockerfile: ./infrastructure/core/Dockerfile
    container_name: core
    environment:
      - OLLAMA_BASE_URL=not-set
    expose:
      - "8000"
    volumes:
      - documents:/data
  webdav:
    build: webdav/
    container_name: webdav
    expose:
      - "8081"
    volumes:
      - documents:/var/lib/webdav/data
volumes:
  documents:
