services:
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - core
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - UPSTREAM_HOST=api
      - UPSTREAM_PORT=8000
  core:
    build:
      context: ../
      dockerfile: ./infrastructure/core/Dockerfile
    container_name: core
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    expose:
      - "8000"

