name: zotero-rag-assistant
services:
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - core
      - webdav
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - UPSTREAM_HOST=api
      - UPSTREAM_PORT=8000

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    restart: unless-stopped
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma:/chroma/chroma

  core:
    build:
      context: ../
      dockerfile: ./infrastructure/core/Dockerfile
    container_name: core
    depends_on:
      - chroma
    environment:
      - OLLAMA_HOST=not-set
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    volumes:
      - documents:/data

  webdav:
    build: webdav/
    container_name: webdav
    depends_on:
      - core
    environment:
      - PORT=8000
      - ROOT_DIR=/var/lib/webdav/data
      - CORE_API_URL=http://core:8000/internal/file-changed
    volumes:
      - documents:/var/lib/webdav/data

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: docker.io/grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_ROOT_URL=http://localhost:8080/grafana/
    volumes:
      - grafana_data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - ./observability/grafana/dashboards:/var/lib/grafana/dashboards

  loki:
    image: docker.io/grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: docker.io/grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./observability/promtail/promtail-config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  node-exporter:
    image: docker.io/prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg

volumes:
  documents:
  chroma:
  prometheus_data:
  grafana_data:
